recipe: default.v1
language: en
assistant_id: campuscompass

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: openai_command_generation_model

policies:
  - name: FlowPolicy

  - name: EnterpriseSearchPolicy
    llm:
      model_group: openai_search_generation_model
    embeddings:
      model_group: openai_embeddings_model
    vector_store:
      type: "faiss"
      source: "./docs"
      loader_kwargs:
        encoding: "utf-8"
